### ISSUE TITLE
Unable to start LSP-Typescript

### ISSUE THREAD

**Issue by MrMid** [sublimelsp/LSP-typescript#169]
Hello, I'm using LSP-Typescript in ST 4137, and recently it stopped being able to start up.

```
Unable to open /home/john/.config/sublime-text-3/Packages/LSP-typescript/LSP-typescript.sublime-settings
Unable to start subprocess for LSP-json
Traceback (most recent call last):
  File "/home/john/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 247, in start_async
    if plugin_class.needs_update_or_installation():
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 108, in get_server
    'skip_npm_install': cls.skip_npm_install,
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 33, in create
    raise Exception('Failed resolving the Node Runtime. Please see Sublime Text console for more information')
Exception: Failed resolving the Node Runtime. Please see Sublime Text console for more information
```

I don't remember making any changes corellated to this (in ST, Node, nor my system).

Can you please lead me how to debug this issue?

```
$ node --version
v12.22.10

$ npm --version
6.14.16
```

I'm using nvm to keep node at version 12. I tried setting that to use current version, but that didn't help.

In LSP-typescript.sublime-settings there is:
`"command": ["${node_bin}", "${server_path}", "--stdio"]`

I suppose there could be wrong path in `node_bin`, but how to debug/set that?

Thank you in advance.

**Comment by predragnikolic** [comment]
Hello,

Closing this issue is as a duplicate.
For more info see https://github.com/sublimelsp/LSP-typescript/issues/162#issuecomment-1244841594

**Comment by MrMid** [comment]
Thank you, I see, commit 75bca930. Where can I find those requirements next time?

Thanks

**Comment by rchl** [comment]
> Thank you, I see, commit [75bca93](https://github.com/sublimelsp/LSP-typescript/commit/75bca930fe7652b6aa8f20d8e69f9e62e383157d). Where can I find those requirements next time?

The error says `Exception: Failed resolving the Node Runtime. Please see Sublime Text console for more information` and the console actually specifies that the version requirement failed but you have missed that one and pasted some other, unrelated error.

**Comment by MrMid** [comment]
Oh, I'm sorry, the error messages got messed up.

```
Unable to start subprocess for LSP-typescript
Traceback (most recent call last):
  File "/home/john/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 247, in start_async
    if plugin_class.needs_update_or_installation():
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 108, in get_server
    'skip_npm_install': cls.skip_npm_install,
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 33, in create
    raise Exception('Failed resolving the Node Runtime. Please see Sublime Text console for more information')
Exception: Failed resolving the Node Runtime. Please see Sublime Text console for more information
```

It look like the LSP-json throws the same error, so the problem probably lies somewhere else. Other LSP servers are working, though.

Unfortunately, using current node version didn't help.

**Comment by rchl** [comment]
There should be a message like `LSP-typescript: Error: Ignoring local Node.js runtime due to an error. Node.js version requirement failed. Expected minimum: ...` before that.

That said, ideally we should surface more relevant error message in the dialog but that would be an issue for https://github.com/sublimelsp/lsp_utils

**Comment by MrMid** [comment]
No, that message isn't present in my console. I started a new instance and the message in my last comment is all there is.
