### ISSUE TITLE
Server install failed

### ISSUE THREAD

**Issue by evamango** [sublimelsp/LSP-typescript#174]
I got this after restart Sublime. Before that it works fine. THX!

# Troubleshooting: LSP-typescript
## Version
 - LSP: 1.19.0
 - Sublime Text: 4134
## Server Test Run
 - exit code: -1
 - output
```
Error installing the server:
Failed to run npm command "/Users/Evans/.nvm/versions/node/v16.13.1/bin/npm ci --scripts-prepend-node-path=true --verbose --production":
npm verb cli [
npm verb cli   '/Users/Evans/.nvm/versions/node/v16.13.1/bin/node',
npm verb cli   '/Users/Evans/.nvm/versions/node/v16.13.1/bin/npm',
npm verb cli   'ci',
npm verb cli   '--scripts-prepend-node-path=true',
npm verb cli   '--verbose',
npm verb cli   '--production'
npm verb cli ]
npm info using npm@8.1.2
npm info using node@v16.13.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/Evans/.nvm/versions/node/v16.13.1/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm verb config production Use `--omit=dev` instead.
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/Evans/Library/Caches/Sublime Text/Package Storage/LSP-typescript/16.13.1/typescript-language-server/.npmrc Completed in 1ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:/Users/Evans/.npmrc Completed in 2ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:/Users/Evans/.nvm/versions/node/v16.13.1/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 2ms
npm timing config:load:credentials Completed in 2ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 15ms
npm timing npm:load:configload Completed in 15ms
npm timing npm:load:setTitle Completed in 16ms
npm timing npm:load:setupLog Completed in 1ms
npm timing config:load:flatten Completed in 3ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 42ms
npm timing arborist:ctor Completed in 4ms
npm timing npm-ci:rm Completed in 4ms
npm timing idealTree:init Completed in 1ms
npm timing idealTree:userRequests Completed in 0ms
npm timing idealTree:#root Completed in 1ms
npm timing idealTree:buildDeps Completed in 1ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 5ms
npm timing reify:loadTrees Completed in 7ms
npm timing reify:diffTrees Completed in 2ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 6ms
npm timing reify:trashOmits Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/universalify Completed in 398ms
npm timing reifyNode:node_modules/yocto-queue Completed in 400ms
npm timing reifyNode:node_modules/unique-string Completed in 400ms
npm timing reifyNode:node_modules/temp-dir Completed in 400ms
npm timing reifyNode:node_modules/tempy Completed in 400ms
npm timing reifyNode:node_modules/pkg-up Completed in 400ms
npm timing reifyNode:node_modules/path-exists Completed in 400ms
npm timing reifyNode:node_modules/p-limit Completed in 400ms
npm timing reifyNode:node_modules/p-locate Completed in 400ms
npm timing reifyNode:node_modules/p-debounce Completed in 400ms
npm timing reifyNode:node_modules/is-stream Completed in 400ms
npm timing reifyNode:node_modules/locate-path Completed in 401ms
npm timing reifyNode:node_modules/lru-cache Completed in 401ms
npm timing reifyNode:node_modules/yallist Completed in 402ms
npm timing reifyNode:node_modules/find-up Completed in 402ms
npm timing reifyNode:node_modules/crypto-random-string Completed in 402ms
npm timing reifyNode:node_modules/which Completed in 404ms
npm timing reifyNode:node_modules/graceful-fs Completed in 404ms
npm timing reifyNode:node_modules/jsonfile Completed in 405ms
npm timing reifyNode:node_modules/isexe Completed in 406ms
npm timing reifyNode:node_modules/deepmerge Completed in 410ms
npm timing reifyNode:node_modules/vscode-languageserver-textdocument Completed in 414ms
npm timing reifyNode:node_modules/commander Completed in 433ms
npm timing reifyNode:node_modules/vscode-uri Completed in 438ms
npm timing reifyNode:node_modules/vscode-languageserver-types Completed in 440ms
npm timing reifyNode:node_modules/fs-extra Completed in 459ms
npm timing reifyNode:node_modules/semver Completed in 460ms
npm timing reifyNode:node_modules/vscode-jsonrpc Completed in 473ms
npm timing reifyNode:node_modules/crypto-random-string/node_modules/type-fest Completed in 473ms
npm timing reifyNode:node_modules/vscode-languageserver Completed in 474ms
npm timing reifyNode:node_modules/type-fest Completed in 477ms
npm timing reifyNode:node_modules/vscode-languageserver-protocol Completed in 481ms
npm http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/advisories/bulk 512ms
npm http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 99ms
npm verb audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
npm verb audit error     at /Users/Evans/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb audit error     at async Map.[getReport] (/Users/Evans/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:337:21)
npm verb audit error     at async Map.run (/Users/Evans/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:107:19)
npm verb audit error  HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
npm verb audit error     at /Users/Evans/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb audit error     at async Map.[getReport] (/Users/Evans/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:337:21)
npm verb audit error     at async Map.run (/Users/Evans/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:107:19) {
npm verb audit error   headers: [Object: null prototype] {
npm verb audit error     server: [ 'Tengine' ],
npm verb audit error     'content-type': [ 'text/html; charset=utf-8' ],
npm verb audit error     'transfer-encoding': [ 'chunked' ],
npm verb audit error     connection: [ 'keep-alive' ],
npm verb audit error     'strict-transport-security': [ 'max-age=5184000' ],
npm verb audit error     date: [ 'Wed, 26 Oct 2022 12:08:08 GMT' ],
npm verb audit error     vary: [ 'Origin' ],
npm verb audit error     'x-frame-options': [ 'SAMEORIGIN' ],
npm verb audit error     'x-xss-protection': [ '1; mode=block' ],
npm verb audit error     'x-content-type-options': [ 'nosniff' ],
npm verb audit error     'x-download-options': [ 'noopen' ],
npm verb audit error     'x-readtime': [ '2.691' ],
npm verb audit error     'content-encoding': [ 'gzip' ],
npm verb audit error     'x-alicdn-da-ups-status': [ 'endOs,0,404' ],
npm verb audit error     via: [ 'cache14.l2et2[25,0], kunlun10.cn257[56,0]' ],
npm verb audit error     'timing-allow-origin': [ '*' ],
npm verb audit error     eagleid: [ 'ab08f29e16667860885618373e' ],
npm verb audit error     'x-fetch-attempts': [ '1' ]
npm verb audit error   },
npm verb audit error   statusCode: 404,
npm verb audit error   code: 'E404',
npm verb audit error   method: 'POST',
npm verb audit error   uri: 'https://registry.npmmirror.com/-/npm/v1/security/audits/quick',
npm verb audit error   body: <Buffer 3c 68 31 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 68 31 3e>,
npm verb audit error   pkgid: undefined
npm verb audit error }
npm timing auditReport:getReport Completed in 624ms
npm timing reify:audit Completed in 625ms
npm http fetch GET 404 https://cdn.npmmirror.com/packages/typescript-language-server/2.1.0/typescript-language-server-2.1.0.tgz 606ms (cache skip)
npm timing reifyNode:node_modules/typescript Completed in 771ms
npm timing reify:rollback:createSparse Completed in 111ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:ci Completed in 956ms
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://cdn.npmmirror.com/packages/typescript-language-server/2.1.0/typescript-language-server-2.1.0.tgz
npm verb stack     at /Users/Evans/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb statusCode 404
npm verb pkgid typescript-language-server@https://registry.npmmirror.com/typescript-language-server/-/typescript-language-server-2.1.0.tgz
npm verb cwd /Users/Evans/Library/Caches/Sublime Text/Package Storage/LSP-typescript/16.13.1/typescript-language-server
npm verb Darwin 21.4.0
npm verb argv "/Users/Evans/.nvm/versions/node/v16.13.1/bin/node" "/Users/Evans/.nvm/versions/node/v16.13.1/bin/npm" "ci" "--scripts-prepend-node-path=true" "--verbose" "--production"
npm verb node v16.13.1
npm verb npm  v8.1.2
npm ERR! code E404
npm ERR! 404 Not Found - GET https://cdn.npmmirror.com/packages/typescript-language-server/2.1.0/typescript-language-server-2.1.0.tgz
npm ERR! 404 
npm ERR! 404  'typescript-language-server@https://registry.npmmirror.com/typescript-language-server/-/typescript-language-server-2.1.0.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit 1
npm timing npm Completed in 1461ms
npm verb unfinished npm timer reify 1666786087951
npm verb unfinished npm timer reify:unpack 1666786087978
npm verb unfinished npm timer reifyNode:node_modules/typescript-language-server 1666786087979
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Evans/.npm/_logs/2022-10-26T12_08_08_864Z-debug.log
```
## Server Configuration
 - command
```json
[
  "/usr/local/bin/node", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh

```
 - selector
```
source.js, source.jsx, source.ts, source.tsx
```
 - priority_selector
```
source.js, source.jsx, source.ts, source.tsx
```
 - init_options
```json
{
  "locale": "en", 
  "logVerbosity": "off", 
  "maxTsServerMemory": 0, 
  "npmLocation": "", 
  "plugins": [], 
  "preferences": {
    "allowIncompleteCompletions": true, 
    "allowRenameOfImportPath": true, 
    "allowTextChangesInNewFiles": true, 
    "autoImportFileExcludePatterns": [], 
    "displayPartsForJSDoc": true, 
    "generateReturnInDocTemplate": true, 
    "includeAutomaticOptionalChainCompletions": true, 
    "includeCompletionsForImportStatements": true, 
    "includeCompletionsForModuleExports": true, 
    "includeCompletionsWithClassMemberSnippets": true, 
    "includeCompletionsWithInsertText": true, 
    "includeCompletionsWithObjectLiteralMethodSnippets": true, 
    "includeCompletionsWithSnippetText": true, 
    "jsxAttributeCompletionStyle": "auto", 
    "providePrefixAndSuffixTextForRename": true, 
    "useLabelDetailsInCompletionEntries": true
  }, 
  "tsserver": {
    "logDirectory": "", 
    "logVerbosity": "off", 
    "path": "", 
    "trace": "off"
  }
}
```
 - settings
```json
{
  "diagnostics": {
    "ignoredCodes": []
  }, 
  "implicitProjectConfiguration": {
    "checkJs": false, 
    "experimentalDecorators": false, 
    "module": "ESNext", 
    "strictFunctionTypes": true, 
    "strictNullChecks": true, 
    "target": "ES2020"
  }, 
  "javascript": {
    "format": {
      "insertSpaceAfterCommaDelimiter": true, 
      "insertSpaceAfterConstructor": false, 
      "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true, 
      "insertSpaceAfterKeywordsInControlFlowStatements": true, 
      "insertSpaceAfterOpeningAndBeforeClosingEmptyBraces": false, 
      "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false, 
      "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false, 
      "insertSpaceAfterSemicolonInForStatements": true, 
      "insertSpaceAfterTypeAssertion": false, 
      "insertSpaceBeforeAndAfterBinaryOperators": true, 
      "insertSpaceBeforeFunctionParenthesis": false, 
      "insertSpaceBeforeTypeAnnotation": false, 
      "placeOpenBraceOnNewLineForControlBlocks": false, 
      "placeOpenBraceOnNewLineForFunctions": false, 
      "semicolons": "ignore", 
      "trimTrailingWhitespace": true
    }, 
    "inlayHints": {
      "includeInlayEnumMemberValueHints": false, 
      "includeInlayFunctionLikeReturnTypeHints": false, 
      "includeInlayFunctionParameterTypeHints": false, 
      "includeInlayParameterNameHints": "none", 
      "includeInlayParameterNameHintsWhenArgumentMatchesName": false, 
      "includeInlayPropertyDeclarationTypeHints": false, 
      "includeInlayVariableTypeHints": false, 
      "includeInlayVariableTypeHintsWhenTypeMatchesName": false
    }
  }, 
  "typescript": {
    "format": {
      "insertSpaceAfterCommaDelimiter": true, 
      "insertSpaceAfterConstructor": false, 
      "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true, 
      "insertSpaceAfterKeywordsInControlFlowStatements": true, 
      "insertSpaceAfterOpeningAndBeforeClosingEmptyBraces": false, 
      "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false, 
      "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false, 
      "insertSpaceAfterSemicolonInForStatements": true, 
      "insertSpaceAfterTypeAssertion": false, 
      "insertSpaceBeforeAndAfterBinaryOperators": true, 
      "insertSpaceBeforeFunctionParenthesis": false, 
      "insertSpaceBeforeTypeAnnotation": false, 
      "placeOpenBraceOnNewLineForControlBlocks": false, 
      "placeOpenBraceOnNewLineForFunctions": false, 
      "semicolons": "ignore", 
      "trimTrailingWhitespace": true
    }, 
    "inlayHints": {
      "includeInlayEnumMemberValueHints": true, 
      "includeInlayFunctionLikeReturnTypeHints": true, 
      "includeInlayFunctionParameterTypeHints": true, 
      "includeInlayParameterNameHints": "literals", 
      "includeInlayParameterNameHintsWhenArgumentMatchesName": true, 
      "includeInlayPropertyDeclarationTypeHints": false, 
      "includeInlayVariableTypeHints": false, 
      "includeInlayVariableTypeHintsWhenTypeMatchesName": false
    }
  }
}
```
 - env
```json
{}
```

## Active view
 - File name
```
/Users/Evans/Project/sanguo/version/release/src/common/event/evt-emitter.ts
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/JavaScript/TypeScript.sublime-syntax"
}
```
 - base scope
```
source.ts
```

## Project / Workspace
 - folders
```json
[
  "/Users/Evans/Project/sanguo/version/release"
]
```
 - is project: False

## LSP configuration

```json
{
  "lsp_code_actions_on_save": {}, 
  "on_save_task_timeout_ms": 500, 
  "show_diagnostics_count_in_view_status": true, 
  "show_diagnostics_panel_on_save": 1, 
  "show_diagnostics_severity_level": 2
}
```
## System PATH
 - /Users/Evans/.rvm/gems/ruby-2.7.2/bin
 - /Users/Evans/.rvm/gems/ruby-2.7.2@global/bin
 - /Users/Evans/.rvm/rubies/ruby-2.7.2/bin
 - /Users/Evans/.nvm/versions/node/v16.13.1/bin
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /Applications/VMware Fusion.app/Contents/Public
 - /usr/local/share/dotnet
 - ~/.dotnet/tools
 - /Library/Apple/usr/bin
 - /Library/Frameworks/Mono.framework/Versions/Current/Commands
 - /Applications/Sublime Text.app/Contents/SharedSupport/bin
 - ||zprofile
 - /Users/Evans/.rvm/bin

**Comment by rchl** [comment]
You have some configured somewhere (maybe in `/Users/Evans/.npmrc`) that overrides the registry used for fetching NPM packages.

The registry mirror used (https://registry.npmmirror.com) doesn't seem to have that package available.

**Comment by evamango** [comment]
> 

You're my hero. It's OK after comment this line in `.npmrc`.
`registry=https://registry.npmmirror.com/`

Many thanks
