### ISSUE TITLE
No completions or hints

### ISSUE THREAD

**Issue by meengit** [sublimelsp/LSP-typescript#55]
Hi all

First of all: I would like to thank all the committers and maintainers for this excellent piece of software.

### Summary

`LSP-typescript` does not provide any hints or completions. However, a custom configuration of the `typescript-language-server`-client in the LSP Settings does it. In a way, I discovered the same effect as @loricheung in https://github.com/sublimelsp/LSP-typescript/issues/54#issue-873851954 but _not_ using any other Packages for Typescript and only [Babel](https://packagecontrol.io/packages/Babel) and [JSCustom](https://packagecontrol.io/packages/JSCustom) sometimes for JavaScript (both disabled at this time).

### Platform

* Device: Apple MacBook Pro 2019
* OS: Apple macOS Big Sur (11.3)
* Application: SublimeText Build 4104

### Description

LSP-typescript does not show any hints or completions in a Typescript project.

### Steps to reproduce

Create a new React.js app using `cra` and the TypeScript template: <https://reactjs.org/docs/static-type-checking.html#typescript>:

```bash
npx create-react-app cra-app --template typescript
```

Change into your newly added React.js/Typescript app and open it in SublimeText:

```bash
cd ./cra-app
subl .
```

Enable LSP-Typescript globally:

![LSP-enable-globally](https://user-images.githubusercontent.com/6507355/116898790-19be1b00-ac37-11eb-9381-85fa01da8671.png)

![LSP-typescript-globally](https://user-images.githubusercontent.com/6507355/116898819-20e52900-ac37-11eb-8ccf-ab011df6aefd.png)

Open `./src/App.tsx` in SublimeText:

![LSP-typescript-completions](https://user-images.githubusercontent.com/6507355/116898870-35c1bc80-ac37-11eb-95d1-3faa9bd5b523.png)

**You should get no result.**

### Logs

LSP provides me no logs – which is very unexpected because typically, the LSP logging is very precise! The only thing I get in SublimeText's console is:

```text
reloading python 3.3 plugin LSP-typescript.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/<USER>/Library/Application Support/Sublime Text/Installed Packages/LSP-typescript.sublime-package/plugin.py", line 7, in <module>
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
```

I also noticed that LSP does show "ok" on the bottom left but no language server name:

![LSP-typescript-footer](https://user-images.githubusercontent.com/6507355/116899064-69044b80-ac37-11eb-9985-27b3157232bd.png)

### Additional context

My LSP logging settings are:

```json
{
  "log_debug": true,
   "log_stderr": true,
   "log_payloads": true,
   "log_server": [
      "panel"
   ]
}
```

#### Tested LSP-typescript settings

1. Customized command and "TSX.sublime-syntax":

```javascript
{
  "command": ["/Users/<USER>/.nvm/versions/node/v14.16.0/bin/node", "/Users/<USER>/.nvm/versions/node/v14.16.0/bin/typescript-language-server", "--stdio"], // custom
  "languages": [
    {
      "languageId": "typescriptreact",
      "scopes": ["source.tsx"],
      "syntaxes": [
        "Packages/TypeScript Syntax/TypeScriptReact.tmLanguage", // set but Package is disabled
        "Packages/TypeScript/TypeScriptReact.tmLanguage", // set but Package is disabled
        "Packages/JavaScript/TSX.sublime-syntax" // custom
      ],
    }
}
```

2. Using the default settings provided by `LSP-typescript`

#### Testedwith Node.js versions:

* v14.16.0 (via nvm)
* v15.11.0 (System in `/usr/local/bin/node`)

### Expected behavior

`LSP-typescript` should show hints and completions in the same or (maybe) a better way as a custom configuration of `typescript-language-server` in `LSP Settings`.

If I set…

```javascript
{
  "clients": {
    "typescript-language-server": {
      "command": ["/usr/local/bin/typescript-language-server", "--stdio"],
        "languages": [
          {
            "languageId": "typescript",
            "scopes": ["source.ts", "source.tsx"],
            "syntaxes": [
            "Packages/TypeScript/TypeScript.tmLanguage",  // set but Package is disabled
            "Packages/TypeScript/TypeScriptReact.tmLanguage", // set but Package is disabled
            "Packages/JavaScript/TSX.sublime-syntax"
            ],
          ],
          "enabled": true,
     },
  }
}
```

… in LSP's settings, then disable `LSP-typescript` globally and enable (my custom) `typescript-language-server` globally, LSP works as expected:

![LSP-tls-globally](https://user-images.githubusercontent.com/6507355/116900264-d2d12500-ac38-11eb-9ba1-fadd0c2bdd53.png)

LSP also shows the language server name at the bottom left:

![LSP-tls-footer](https://user-images.githubusercontent.com/6507355/116900332-ec726c80-ac38-11eb-95b0-ae5a0e5dbca7.png)

### Various

* Any steps referencing "LSP enable globally" also have the same effect when I enable `LSP-typescript` or `typescript-language-server` in a SublimeText project.
* For `LSP-typescript` the LSP log panel is always empty.
* For LSP with custom `typescript-language-server`-client, the LSP log panel works as expected.
* I hadn't this issue before SublimeText Build 4104.

Troubleshooting `LSP-typescript`:

![LSP-typescript-troubleshooting](https://user-images.githubusercontent.com/6507355/116900535-20e62880-ac39-11eb-8a0b-5c8ddc21266b.png)

Troubleshooting custom `typescript-language-server`-client:

![LSP-tls-troubleshooting](https://user-images.githubusercontent.com/6507355/116900619-38251600-ac39-11eb-8c51-de86515cdd67.png)

### Finally

Did I do something wrong? Or is (really) it a bug/issue?

**Comment by rwols** [comment]
Try running Package Control: Satisfy Dependencies. Then restart ST.

**Comment by meengit** [comment]
Thank you very much for your fast reply @rwols. It looks like `Satisfy Dependencies` does not affect. The issue is still present.

**Comment by rwols** [comment]
Well, the problem seems to be that EnumMeta cannot be imported in sublime_lib, a dependency of this package. Perhaps @FichteFoll or @Thom1729, the maintainers of sublime_lib, can provide more insight into the problem.

**Comment by Thom1729** [comment]
Have you tried restarting Sublime?

I can't think of any reason why it should fail to import the enum stuff there. The complete code of the `_compat.enum` module is:

```py
try:
    from enum import *  # noqa: F401, F403
except ImportError:
    from ..vendor.python.enum import *  # type: ignore # noqa: F401, F403
```

So it's using the default `enum` module if it's available (which is — ironically — mostly for the benefit of tooling) and otherwise uses a vendored version.

The latest update did slightly change this. Before, it always used the vendored library rather than an existing one. My two random guesses are:

1. Something is providing an `enum` module, but for some reason `sublime_lib` doesn't like it.
2. Your install of `sublime_lib` was just updated and it's in some kind of weird state.

If it's (2), then restarting Sublime should fix it. If not, we might need to revert the recent enum change.

**Comment by meengit** [comment]
@Thom1729, yes, to be sure to times. I also removed and re-installed `LSP` and `LSP-typescript`.

Actually, it looks to me that every `LSP-*` package is affected:

```text
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/<USER>/Library/Application Support/Sublime Text/Installed Packages/JSCustom.sublime-package/plugin.py", line 3, in <module>
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
reloading python 3.3 plugin LSP-bash.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/<USER>/Library/Application Support/Sublime Text/Installed Packages/LSP-bash.sublime-package/plugin.py", line 1, in <module>
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
reloading python 3.3 plugin LSP-dockerfile.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/<USER>/Library/Application Support/Sublime Text/Installed Packages/LSP-dockerfile.sublime-package/plugin.py", line 2, in <module>
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
reloading python 3.3 plugin LSP-intelephense.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/<USER>/Library/Application Support/Sublime Text/Installed Packages/LSP-intelephense.sublime-package/plugin.py", line 2, in <module>
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
reloading python 3.3 plugin LSP-json.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/<USER>/Library/Application Support/Sublime Text/Installed Packages/LSP-json.sublime-package/plugin.py", line 5, in <module>
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
reloading python 3.3 plugin LSP-pyright.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/<USER>/Library/Application Support/Sublime Text/Installed Packages/LSP-pyright.sublime-package/plugin.py", line 3, in <module>
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
reloading python 3.3 plugin LSP-yaml.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/<USER>/Library/Application Support/Sublime Text/Installed Packages/LSP-yaml.sublime-package/plugin.py", line 1, in <module>
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/<USER>/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
```

For example: if I try to use `LSP-yaml`, I have the same effect as above. `LSP-yaml` itself does not run but if I configure a client in LSP Settings…

```json
{
  "clients": {
    "yaml-language-server": {
      "command": ["/usr/local/bin/yaml-language-server", "--stdio"],
        "enabled": false,
        "scopes": ["source.yaml"],
	"syntaxes": [
	  "Packages/YAML/YAML.sublime-syntax",
	]
      }
  }
}

…it works.

I suggest that I try to dig deeper before you think about reverting the changes.

**Comment by rwols** [comment]
What is your list of installed packages? I’m wondering if one has a python module named `enum`.

**Comment by meengit** [comment]
@Thom1729 & @rwols 

@tom & @rwols, I did further tests:

* Remove `lsp-typescript` using Package Control
* Deleted `Package Storage/LSP-typescript` manually
* Restarted SublimeText
* Reinstalled `LSP-typescript`

**Result: no effect; the issue persists**

* Closed SublimeText
* Deleted `Packages/sublime_lib manually`
* Restarted SublimeText
* `Packages/sublime_lib` installs automatically 

![lib](https://user-images.githubusercontent.com/6507355/116919329-67478180-ac51-11eb-91aa-0efdc53b01b1.png)

* Restarted SublimeText

**Result: no effect; the issue persists**

* Closed SublimeText
* Deleted `Packages/sublime_lib`manually
* Deleted `Cache/sublime_lib`manually
* Restarted SublimeText
* `Packages/sublime_lib` installs automatically 

![lib](https://user-images.githubusercontent.com/6507355/116919329-67478180-ac51-11eb-91aa-0efdc53b01b1.png)

* Restarted SublimeText

**Result: no effect; the issue persists**

**Comment by Thom1729** [comment]
Can you run the following in the **3.3** console? (To specify Python 3.3, right-click on the console input field and choose it.)

```py
import enum; enum.__file__
```

Ordinarily, this should raise an `ImportError`. If another package is providing an `enum` module, this should tell us what package. (If the result is `'/Applications/Sublime Text.app/Contents/MacOS/Lib/python3.8.zip/enum.pyc'`, then you ran the command in 3.8 instead.)

Another thing that might shed light on the issue (also in 3.3):

```py
import sublime_lib._compat.enum; dir(sublime_lib._compat.enum)
```

For me, the result is `['Enum', 'EnumMeta', 'Flag', 'IntEnum', 'IntFlag', '__builtins__', '__cached__', '__doc__', '__file__', '__initializing__', '__loader__', '__name__', '__package__', 'auto', 'unique']`. If there's another

**Comment by meengit** [comment]
@rwols, currently enabled are:

```text
✔ All Autocomplete                                           
✔ ApacheConf                                            
✔ AsciiDoc                                                   
✔ BracketHighlighter                                    
✔ ColorHelper                                           
✔ CSS3                                                       
✔ Debugger                                              
✔ Dockerfile Syntax Highlighting                             
✔ EditorConfig                                               
✔ File History                                               
✔ Generic Config                                             
✔ Gist                                                  
✔ Github Tools                                               
✔ HyperClick                                                 
✔ Indent XML                                                 
✔ JsPrettier                                            
✔ LSP                                                   
✔ LSP-bash                                                   
✔ LSP-dockerfile                                             
✔ LSP-intelephense                                           
✔ LSP-json                                              
✔ LSP-pyright                                           
✔ LSP-typescript                                        
✔ LSP-yaml                                                   
✔ Marked App Menu                                       
✔ OrgExtended                                                
✔ Origami                                               
✔ Package Control                                       
✔ PackagesUI                                                 
✔ PlainNotes                                                 
✔ PowerShell                                            
✔ Pretty JSON                                                
✔ RegReplace                                            
✔ SFTP                                                  
✔ ShellCommand                                               
✔ ST-TodoReview                                              
✔ SublimeLinter                                              
✔ SublimeLinter-annotations                             
✔ SublimeLinter-contrib-ansible-lint                         
✔ SublimeLinter-contrib-mypy                                 
✔ SublimeLinter-contrib-terraform                       
✔ SublimeLinter-contrib-yamllint                             
✔ SublimeLinter-eslint                                  
✔ SublimeLinter-flake8                                                               
✔ SublimeLinter-rubocop                                 
✔ SublimeLinter-shellcheck                                   
✔ Terminus                                              
✔ Terraform                                                  
✔ Vue Syntax Highlight                                       
✔ Wallaby                                               
```

Does it matter if a package is installed but disabled (ignored). I have a lot of packages installed but usually ignore all packages I don't need for the current project.

**Comment by meengit** [comment]
@Thom1729

```text
Python 3.3>>> import enum; enum.__file__
'/Users/run/Library/Application Support/Sublime Text/Packages/enum/all/enum/__init__.py'
```

and

```text
Python 3.3>>> import sublime_lib._compat.enum; dir(sublime_lib._compat.enum)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/run/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/__init__.py", line 1, in <module>
    from .panel import Panel, OutputPanel  # noqa: F401
  File "/Users/run/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/panel.py", line 4, in <module>
    from .view_utils import set_view_options, validate_view_options
  File "/Users/run/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/view_utils.py", line 7, in <module>
    from ._util.enum import ExtensibleConstructorMeta, construct_with_alternatives
  File "/Users/run/Library/Application Support/Sublime Text/Packages/sublime_lib/st3/sublime_lib/_util/enum.py", line 3, in <module>
    from .._compat.enum import EnumMeta, Enum, Flag
ImportError: cannot import name EnumMeta
```

**Comment by Thom1729** [comment]
After some investigation, I suspect that one of your packages requires the `enum34` dependency. That dependency provides an `enum` module, but it does not support all of the features that `sublime_lib`'s vendored `enum` does. Probably sublime_lib needs to stop using existing `enum` modules and unconditionally use the vendored version. I'll write up a fix ASAP.

**Comment by meengit** [comment]
Thank you very much for your ***fantastic*** support @Thom1729 and @rwols.

> Does it matter if a package is installed but disabled (ignored)?

@rwols, yes, I think it matters because as far as I can see, once a package is installed, it also "places" its dependencies. (Probably something you know already.)

@Thom, in my case, it was the (disabled) [`Deviot`](https://packagecontrol.io/packages/Deviot%20(Arduino%20IDE)) Package that placed `Packages/enum` in my Packages directory. I removed `Deviot` using `Package Control` and deleted the `Packages/enum` directory manually. Now, all "blocked" `LSP-*` packages are working as expected.

**The issue is fixed!**
