### ISSUE TITLE
Global name 'path' is not defined

### ISSUE THREAD

**Issue by gribera** [sublimelsp/LSP-typescript#65]
Hi, I am having a problem using LSP-typescript with Sublime Text 4 (4107)

When I open a typescript file it throws me the following error:

![image](https://user-images.githubusercontent.com/5048239/122499947-32587980-cfc8-11eb-83dc-fbe62a59e20e.png)

Does anyone know what may be happening?

Sublime log:

```

startup, version: 4107 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
application: /opt/sublime_text
working dir: /home/gonza
packages path: /home/gonza/.config/sublime-text-3/Packages
state path: /home/gonza/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/gonza/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.166196
startup time: 0.306299
first paint time: 0.313616
git: located Sublime Merge installed at /opt/sublime_merge
git: using configuration from system git install
git: tracking working dir /home/gonza/Proyectos/ungs/nest/api-server
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading python 3.3 plugin 0_package_control_loader.01-pygments
reloading python 3.3 plugin 0_package_control_loader.01-sublime_lib
reloading python 3.3 plugin 0_package_control_loader.10-lsp_utils
reloading python 3.3 plugin 0_package_control_loader.50-backrefs
reloading python 3.3 plugin 0_package_control_loader.50-bracex
reloading python 3.3 plugin 0_package_control_loader.50-markupsafe
reloading python 3.3 plugin 0_package_control_loader.50-pymdownx
reloading python 3.3 plugin 0_package_control_loader.50-python-markdown
reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
reloading python 3.3 plugin 0_package_control_loader.51-python-jinja2
reloading python 3.3 plugin 0_package_control_loader.55-jsonschema
reloading python 3.3 plugin 0_package_control_loader.55-mdpopups
reloading python 3.3 plugin 0_package_control_loader.55-wcmatch
reloading python 3.3 plugin Alignment.Alignment
reloading python 3.3 plugin ayu.activation
reloading python 3.3 plugin ayu.Icons
reloading python 3.3 plugin BracketHighlighter.bh_core
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin A File Icon.plugin
reloading plugin Emmet.main
reloading plugin MoveTab.move_tab
reloading python 3.3 plugin BracketHighlighter.bh_logging
reloading python 3.3 plugin BracketHighlighter.bh_plugin
reloading python 3.3 plugin BracketHighlighter.bh_popup
reloading python 3.3 plugin BracketHighlighter.bh_regions
reloading python 3.3 plugin BracketHighlighter.bh_remove
reloading python 3.3 plugin BracketHighlighter.bh_rules
reloading python 3.3 plugin BracketHighlighter.bh_search
reloading python 3.3 plugin BracketHighlighter.bh_swapping
reloading python 3.3 plugin BracketHighlighter.bh_wrapping
reloading python 3.3 plugin BracketHighlighter.support
reloading python 3.3 plugin DocBlockr.jsdocs
reloading python 3.3 plugin GitGutter.plugin
reloading python 3.3 plugin LSP-typescript.plugin
reloading python 3.3 plugin LSP.boot
reloading python 3.3 plugin MarkdownPreview.markdown_preview
reloading python 3.3 plugin MarkdownPreview.markdown_settings
reloading python 3.3 plugin MarkdownPreview.markdown_wrapper
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin SCSS.scss_completions
reloading python 3.3 plugin SublimeLinter-eslint.linter
reloading python 3.3 plugin SublimeLinter.__init__
reloading python 3.3 plugin SublimeLinter._init
reloading python 3.3 plugin SublimeLinter.active_linters_view
reloading python 3.3 plugin SublimeLinter.busy_indicator_view
reloading python 3.3 plugin SublimeLinter.goto_commands
reloading python 3.3 plugin SublimeLinter.highlight_view
reloading python 3.3 plugin SublimeLinter.log_handler
reloading python 3.3 plugin SublimeLinter.message_view
reloading python 3.3 plugin SublimeLinter.panel_view
reloading python 3.3 plugin SublimeLinter.quick_actions
reloading python 3.3 plugin SublimeLinter.status_bar_view
reloading python 3.3 plugin SublimeLinter.sublime_linter
reloading python 3.3 plugin TypescriptCompletion.TSCompletion
reloading python 3.3 plugin ColorPicker.sublimecp
reloading python 3.3 plugin JsPrettier.JsPrettier
reloading python 3.3 plugin SFTP.SFTP
reloading python 3.3 plugin TypeScript.main
2021-06-18 00:01:44,621: 139766646654784: WARNING: TypeScript plugin initialized.
WARNING:TS:TypeScript plugin initialized.
plugins loaded
Path of node executable is configured as: /usr/bin/node
Unable to start subprocess for LSP-typescript
Traceback (most recent call last):
  File "/home/gonza/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 320, in start_async
    cwd = plugin_class.on_pre_start(self._window, initiating_view, workspace_folders, config)
  File "/home/gonza/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 130, in on_pre_start
    extra_paths = path.pathsep.join(cls.get_additional_paths())
NameError: global name 'path' is not defined

generating syntax summary
Package Control: Skipping automatic upgrade, last run at 2021-06-17 23:26:35, next run at 2021-06-18 00:26:35 or after
```

# Troubleshooting: LSP-typescript
## Version
 - LSP: 1.6.0
 - Sublime Text: 4107
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
/usr/bin/node "/home/gonza/.cache/sublime-text-3/Package Storage/LSP-typescript/15.14.0/typescript-language-server/node_modules/typescript-language-server/lib/cli.js" --stdio
```
 - selector
```
(source.jsx | source.js.react)|(source.js)|(source.tsx)|(source.ts)
```
 - priority_selector
```
(source.javascriptreact)|(source.javascript)|(source.typescriptreact)|(source.typescript)
```
 - init_options
```json
{}
```
 - settings
```json
{}
```
 - env
```json
{}
```

## Active view
 - File name
```
/home/gonza/Proyectos/ungs/nest/api-server/src/modules/sudocu/area/area.controller.ts
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag - punctuation.definition.tag.begin, source - comment - string.quoted.double.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/TypeScript/TypeScript.tmLanguage"
}
```
 - base scope
```
source.ts
```

## Project / Workspace
 - folders
```json
[
  "/home/gonza/Proyectos/ungs/nest/api-server"
]
```
 - is project: False

## LSP configuration

<not found>
## System PATH
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/local/games
 - /usr/games

**Comment by predragnikolic** [comment]
There is a new release that will fix the problem. 

https://github.com/sublimelsp/lsp_utils/releases/tag/1.13.3

**Comment by rchl** [comment]
Run `Package Control: Satisfy Dependencies` from the Command Palette to get the fix quicker.

**Comment by rchl** [comment]
Version 1.13.3 is now available

**Comment by gribera** [comment]
thanks, it worked!
