### ISSUE TITLE
v1.2.5 onward doesn't work in ST3

### ISSUE THREAD

**Issue by dangh** [sublimelsp/LSP-typescript#68]
This is the error in the latest version which boil down to this [commmit](https://github.com/sublimelsp/LSP-typescript/commit/f33903b0cf846095f86c6141f57fa9cfdbbe6800)

```
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'LSP-typescript.plugin'
```

I know ST3 is no longer supported as ST4 has been out. Could we tag v1.2.5 onward as ST4 only?

**Comment by rchl** [comment]
There was no intention to break for the time being so it's just a bug that should be fixed.

BTW the actual error is `ImportError: cannot import name apply_workspace_edit`

**Comment by rchl** [comment]
Should be fine now.

**Comment by dangh** [comment]
Thank you so much for the fix.
